export const ADD_CLIENT = 'ADD_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const ACTIVATE_EDITING = 'ACTIVATE_EDITING';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM';
